"""Core enumerations for the payment exception resolution system."""

from enum import StrEnum


class PaymentRail(StrEnum):
    SWIFT = "SWIFT"
    ACH = "ACH"
    UPI = "UPI"
    NEFT = "NEFT"
    SEPA = "SEPA"
    INTERNAL = "INTERNAL"


class PaymentType(StrEnum):
    DOMESTIC = "DOMESTIC"
    WIRE = "WIRE"
    BOOK_TRANSFER = "BOOK_TRANSFER"
    DISBURSEMENT = "DISBURSEMENT"


class ExceptionType(StrEnum):
    INCORRECT_BENEFICIARY = "INCORRECT_BENEFICIARY"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    DUPLICATE = "DUPLICATE"
    COMPLIANCE_HOLD = "COMPLIANCE_HOLD"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    CUTOFF_MISS = "CUTOFF_MISS"
    UNCERTAIN_RETRY = "UNCERTAIN_RETRY"


class CaseStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    INVESTIGATING = "INVESTIGATING"
    EVIDENCE_COMPLETE = "EVIDENCE_COMPLETE"
    DECIDING = "DECIDING"
    ACTION_TAKEN = "ACTION_TAKEN"
    MONITORING = "MONITORING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"
    HELD = "HELD"
    AWAITING_INPUT = "AWAITING_INPUT"
    CANCELLED = "CANCELLED"


class Priority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ResolutionAction(StrEnum):
    AUTO_RETRY = "AUTO_RETRY"
    REPAIR_AND_RETRY = "REPAIR_AND_RETRY"
    HOLD_PENDING_FUNDS = "HOLD_PENDING_FUNDS"
    HOLD_PENDING_INPUT = "HOLD_PENDING_INPUT"
    CANCEL_SAFELY = "CANCEL_SAFELY"
    ESCALATE_COMPLIANCE = "ESCALATE_COMPLIANCE"
    ESCALATE_OPERATIONS = "ESCALATE_OPERATIONS"
    DEFER_TO_NEXT_CYCLE = "DEFER_TO_NEXT_CYCLE"


class Confidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INCONCLUSIVE = "INCONCLUSIVE"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class EvidenceType(StrEnum):
    TRANSACTION_STATUS = "TRANSACTION_STATUS"
    ACCOUNT_BALANCE = "ACCOUNT_BALANCE"
    BENEFICIARY_VALIDATION = "BENEFICIARY_VALIDATION"
    COMPLIANCE_CHECK = "COMPLIANCE_CHECK"
    NETWORK_STATUS = "NETWORK_STATUS"
    RETRY_HISTORY = "RETRY_HISTORY"
    DUPLICATE_CHECK = "DUPLICATE_CHECK"
